cards/urls.py
from django.urls import path

from . import views

app_name = "cards"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:card_id>/', views.edit, name="edit"),
    path('add_json', views.add_json, name="json"),
]

decks/urls.py
from django.urls import path

from . import views

app_name = "decks"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:deck_id>/', views.detail, name="deck"),
    path('cards/<int:deck_card_id>/', views.edit_card, name="edit_card"),
]

decks/models.py
from django.db import models
from cards.models import Card,Type

TYPE_LIST = ["Creature","Instant","Sorcery","Enchantment","Artifact"]

class DeckType(models.Model):
    name = models.CharField(max_length=200)
    sort_order = models.SmallIntegerField(default=0)

    def sorted_decks(self):
        return self.deck_set.all().order_by("name")


class Deck(models.Model):
    name = models.CharField(max_length=200)
    deckType = models.ForeignKey(DeckType,on_delete=models.CASCADE)
    notes = models.TextField(blank=True)

    def deck_list(self):
        return self.deckcard_set.filter(count__gt=0).order_by('-commander','card__name')
        
    def deck_list_cmc(self):
        unsorted_list = self.deckcard_set.filter(count__gt=0).all()
        return sorted(unsorted_list, key = lambda t: t.card.cmc_num())
        
    def deck_list_type(self):
        unsorted_list = self.deckcard_set.filter(count__gt=0).all()
        return sorted(unsorted_list, key = lambda t: t.card.regular_types())

    def sidebord(self):
        return self.deckcard_set.filter(sideboard_count__gt=0).order_by('card__name')

    def card_count(self):
        return self.deckcard_set.all().aggregate(models.Sum('count'))['count__sum']

    def mana_curve(self):
        rv = [0]
        for dc in self.deckcard_set.filter(count__gt=0):
            if dc.card.manaCost != "":
                ind = dc.card.cmc()
                while ind >= len(rv):
                    rv.append(0)
                rv[ind] += dc.count
        return rv

    def sideboard(self):
        return self.deckcard_set.filter(sideboard_count__gt=0).order_by('card__name')

    def sideboard_count(self):
        return self.deckcard_set.all().aggregate(models.Sum('sideboard_count'))['sideboard_count__sum']

    def deck_set_list(self):
        basic = Type.objects.filter(typeType=2,name__iexact="basic")[0]
        rv = {}
        for dc in self.deckcard_set.all():
            if dc.card.types.filter(pk=basic.id).exists():
                if "Basic Land" in rv:
                    rv["Basic Land"].append(dc)
                else:
                    rv["Basic Land"] = [dc]
            elif not dc.card.set_set.all().exists():
                if "No Set" in rv:
                    rv["No Set"].append(dc)
                else:
                    rv["No Set"] = [dc]
            else:
                for set in dc.card.set_set.all():
                    if set.name in rv:
                        rv[set.name].append(dc)
                    else:
                        rv[set.name] = [dc]
        return rv

    def card_colours(self):
        rv = {}
        for dc in self.deckcard_set.filter(count__gt=0):
            c = dc.card.colours()
            if c > 0:
                lbl = ""
                if c & 1 > 0:
                    lbl = "White"
                if c & 2 > 0:
                    if len(lbl) > 0:
                        lbl += "/"
                    lbl += "Blue"
                if c & 4 > 0:
                    if len(lbl) > 0:
                        lbl += "/"
                    lbl += "Black"
                if c & 8 > 0:
                    if len(lbl) > 0:
                        lbl += "/"
                    lbl += "Red"
                if c & 16 > 0:
                    if len(lbl) > 0:
                        lbl += "/"
                    lbl += "Green"
                if lbl in rv:
                    rv[lbl] += dc.count
                else:
                    rv[lbl] = dc.count
        return rv

    def card_dots(self):
        rv = {}
        for dc in self.deckcard_set.filter(count__gt=0):
            for m in dc.card.manaArr():
                if len(m) > 0:
                    lbl = ""
                    if m[0] == "W":
                        lbl = "White"
                    elif m[0] == "U":
                        lbl = "Blue"
                    elif m[0] == "B":
                        lbl = "Black"
                    elif m[0] == "R":
                        lbl = "Red"
                    elif m[0] == "G":
                        lbl = "Green"
                    if len(m) > 1 and m[1] != "P":
                        if m[1] == "W":
                            lbl += "/White"
                        elif m[1] == "U":
                            lbl += "/Blue"
                        elif m[1] == "B":
                            lbl += "/Black"
                        elif m[1] == "R":
                            lbl += "/Red"
                        elif m[1] == "G":
                            lbl += "/Green"
                    if len(lbl) > 0:
                        if lbl in rv:
                            rv[lbl] += dc.count
                        else:
                            rv[lbl] = dc.count
        return rv
    
    def types(self):
        rv = dict.fromkeys(TYPE_LIST, 0)
        for dc in self.deckcard_set.all():
            for t in dc.card.types.all():
                if t.name in rv:
                    rv[t.name] += 1
        return rv

    def land(self):
        rv = []
        if len(self.deckcard_set.all()) > 0:
            land_type = Type.objects.filter(typeType=3,name__iexact="land")[0]
            for dc in self.deckcard_set.all().order_by("card__name"):
                if dc.card.types.filter(pk=land_type.id).exists():
                    rv.append(dc)
        return rv

    def land_count(self):
        rv = 0
        if len(self.deckcard_set.all()) > 0:
            land_type = Type.objects.filter(typeType=3,name__iexact="land")[0]
            for dc in self.deckcard_set.all().order_by("card__name"):
                if dc.card.types.filter(pk=land_type.id).exists():
                    rv += dc.count
        return rv


class DeckCard(models.Model):
    card = models.ForeignKey(Card,on_delete=models.CASCADE)
    count = models.SmallIntegerField(default=0)
    deck = models.ForeignKey(Deck,on_delete=models.CASCADE)
    commander = models.BooleanField(default=False)
    sideboard_count = models.SmallIntegerField(default=0)

decks/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from .models import Deck, DeckCard, DeckType
from cards.models import Card, Set, Type

import os, json, re

bad_set_types = ["promo","funny","archenemy","starter","memorabilia"]

def mobile(request):
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)

    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False

# Create your views here.
def index(request):
    try:
        action = request.POST['action']
        if action != "reset":
            arr = json.loads(action)
            ids = []
            for i, val in enumerate(arr):
                try:
                    id = int(val)
                    ids.append(id)
                    dt = DeckType(pk=id)
                    dt.name = request.POST['name-{}'.format(id)]
                    dt.sort_order = i
                    dt.save()
                except ValueError:
                    dt = DeckType(name=val,sort_order=i)
                    dt.save()
                    ids.append(dt.id)
            to_delete = DeckType.objects.exclude(id__in=ids)
            for dt in to_delete:
                dt.delete()
    except KeyError:
        pass
    context = {"deck_types":DeckType.objects.all().order_by('sort_order','name')}
    if mobile(request):
        return render(request, 'decks/m_index.html', context)
    else:
        return render(request, 'decks/index.html', context)

def add(request):
    try:
        context = {"decks":Deck.objects.all().order_by('name'),"deck_types":DeckType.objects.all().order_by('sort_order','name')}
        name = request.POST['name'].strip()
        if len(name) > 0:
            d = Deck(name=name,notes=request.POST['notes'],deckType=DeckType.objects.get(pk=int(request.POST['deckType'])))
            d.save()
            if request.POST['inputType'] == "X":
                p = re.compile("(\\d+)x (.+)")
            else:
                p = re.compile("(\\d+) (.+)")
            issue_list = []
            cards = None
            if len(request.POST['list'].strip().replace('\r\n','\n')) != 0:
                main = request.POST['list'].strip().replace('\r\n','\n').split('\n')
            else:
                main = []
            if len(request.POST['sideboard'].strip().replace('\r\n','\n')) != 0:
                total = main + request.POST['sideboard'].strip().replace('\r\n','\n').split('\n')
            else:
                total = main
            for i,line in enumerate(total):
                m = p.match(line.strip())
                if m is None:
                    issue_list.append("Line {} is badly formed. Card could not be added.".format(line))
                else:
                    c = Card.objects.filter(name__iexact=m.groups()[1])
                    if len(c) == 0:
                        #try json
                        if cards is None:
                            f = open(os.path.join(settings.BASE_DIR, 'AtomicCards.json'),'r',encoding='utf8')
                            cards = json.load(f)["data"]
                            f.close()
                        if m.groups()[1] in cards:
                            c = Card(name=m.groups()[1],
                                text=cards[m.groups()[1]][0]['text'],
                                notes="",
                                addMana=False)
                            #mana cost
                            if "manaCost" in cards[m.groups()[1]][0]:
                                c.manaCost = cards[m.groups()[1]][0]['manaCost'].replace('}{',',').replace('{','').replace('}','').replace('/','')
                            #ptl
                            if "power" in cards[m.groups()[1]][0]:
                                c.power = cards[m.groups()[1]][0]["power"]
                            if "toughness" in cards[m.groups()[1]][0]:
                                c.toughness = cards[m.groups()[1]][0]["toughness"]
                            if "loyalty" in cards[m.groups()[1]][0]:
                                c.loyalty = cards[m.groups()[1]][0]["loyalty"]
                            c.save()
                            #types
                            if "supertypes" in cards[m.groups()[1]][0]:
                                for type in cards[m.groups()[1]][0]['supertypes']:
                                    t = Type.objects.filter(name__exact=type,typeType__exact=2)
                                    if len(t) == 0:
                                        t = Type(name=type,typeType=2)
                                        t.save()
                                    else:
                                        t = t[0]
                                    c.types.add(t)
                            if "types" in cards[m.groups()[1]][0]:
                                for type in cards[m.groups()[1]][0]['types']:
                                    t = Type.objects.filter(name__exact=type,typeType__exact=3)
                                    if len(t) == 0:
                                        t = Type(name=type,typeType=3)
                                        t.save()
                                    else:
                                        t = t[0]
                                    c.types.add(t)
                            if "subtypes" in cards[m.groups()[1]][0]:
                                for type in cards[m.groups()[1]][0]['subtypes']:
                                    t = Type.objects.filter(name__exact=type,typeType__exact=1)
                                    if len(t) == 0:
                                        t = Type(name=type,typeType=1)
                                        t.save()
                                    else:
                                        t = t[0]
                                    c.types.add(t)
                            #sets
                            f = open(os.path.join(settings.BASE_DIR, 'SetList.json'),'r',encoding='utf8')
                            sets = json.load(f)["data"]
                            f.close()
                            if "printings" in cards[m.groups()[1]][0]:
                                for code in cards[m.groups()[1]][0]["printings"]:
                                    for jset in sets:
                                        if jset["code"] == code:
                                            if jset["type"] not in bad_set_types:
                                                set = Set.objects.filter(name__exact=jset["name"])
                                                if len(set) == 0:
                                                    set = Set(name=jset["name"])
                                                    set.save()
                                                else:
                                                    set = set[0]
                                                set.cards.add(c)
                                            break
                            if i < len(main):
                                dc = DeckCard(card=c,count=int(m.groups()[0]),deck=d)
                            else:
                                dc = DeckCard(card=c,sideboard_count=int(m.groups()[0]),deck=d)
                            dc.save()
                        else:
                            issue_list.append("Could not find a card named {}. Card could not be added.".format(m.groups()[1]))
                    else:
                        if i < len(main):
                            dc = DeckCard(card=c[0],count=int(m.groups()[0]),deck=d)
                        else:
                            dc = DeckCard(card=c[0],sideboard_count=int(m.groups()[0]),deck=d)
                        dc.save()
            if len(issue_list) > 0:
                context['saved'] = '\\n'.join(issue_list)
                context['new_deck'] = d.id
            else:
                return redirect('/decks/{}'.format(d.id))
        else:
            context['error'] = "Deck must have a name."
        if mobile(request):
            return render(request, 'decks/m_add.html', context)
        else:
            return render(request, 'decks/add.html', context)
    except KeyError:
        if mobile(request):
            return render(request, 'decks/m_add.html', context)
        else:
            return render(request, 'decks/add.html', context)
    except OSError as ex:
        print(ex)

def detail(request, deck_id):
    context = None
    try:
        action = request.POST['action']
        if action == 'delete':
            Deck.objects.get(pk=deck_id).delete()
            return redirect('/decks/')
        elif action == 'update':
            d = Deck.objects.get(pk=deck_id)
            d.name = request.POST["name"]
            d.deckType = DeckType.objects.get(pk=int(request.POST['deckType']))
            d.notes = request.POST["notes"]
            d.save()
            for dc in d.deckcard_set.all():
                if 'count-{}'.format(dc.id) in request.POST:
                    dc.count = int(request.POST['count-{}'.format(dc.id)])
                if 'sideboard_count-{}'.format(dc.id) in request.POST:
                    dc.sideboard_count = int(request.POST['sideboard_count-{}'.format(dc.id)])
                if dc.count == 0 and dc.sideboard_count == 0:
                    dc.delete()
                else:
                    dc.save()
        elif action == 'ui':
            if "show_only_missing" in request.POST:
                context = {"show_only_missing":"show_only_missing"}
                request.session['show_only_missing'] = True
            else:
                request.session['show_only_missing'] = False
            if "show_extra" in request.POST:
                context = {"show_extra":"show_extra"}
                request.session['show_extra'] = True
            else:
                request.session['show_extra'] = False

decks/templates/decks/add.html
{% load static %}
<head>
    <title>Magic Library - Decks</title>
    <link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
    <style>
        .addBorder {
            border-collapse: collapse;
        }

        .addBorder, .addBorder td, .addBorder th {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h1>Magic Library - Decks</h1>
    {% include "decks/horizontal_navigation_bar.html" with page_name="add" %}
    <div style="margin-top:10px; float:left">
        <form id="frmMain" action="{% url 'decks:add' %}" method="post">
            {% csrf_token %}
            <div>Deck Name</div>
            <div style="margin-top:10px"><input type="text" name="name" /></div>
            <div style="margin-top:10px">
                Deck Type
                <select name="deckType">
                    {% for dt in deck_types %}
                    <option value="{{dt.id}}">{{dt.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div style="margin-top:10px; margin-bottom:10px; float:left">
                <div>Deck List</div>
                <div style="font-size:small">
                    <input type="radio" name="inputType" id="input1" checked value="X"><label for="input1">&lt;count&gt;x &lt;card name&gt;</label>
                    <input type="radio" name="inputType" id="input2" value="plain"><label for="input2">&lt;count&gt; &lt;card name&gt;</label>
                </div>
                <div style="margin-top:10px"><textarea name="list" cols="25" rows="20"></textarea></div>
            </div>
            <div style="margin-top:10px; margin-bottom:10px; margin-left:10px; float:left">
                <div>Sideboard List</div>
                <div style="margin-top:10px"><textarea name="sideboard" cols="25" rows="20"></textarea></div>
            </div>
            <div style="float:left; margin-left: 10px">
                <div style="margin-top:10px">Notes</div>
                <div style="margin-top:10px"><textarea name="notes" cols="50" rows="10"></textarea></div>
            </div>
            <div style="clear: both">
                <input type="submit" value="Save" />
                <input type="button" value="Cancel" onclick="window.location.href='{% url 'decks:index' %}';" />
            </div>
        </form>
    </div>
    {% if error %}
    <div style="margin-top:10px;float:left;text-color:red">{{ error }}</div>
    {% endif %}
    {% if saved %}
    <div class="gray" style="display:block">
        <div class="popup">
            <div>Issue with Deck List</div>
            <div>{{saved}}</div>
            <div><input type="button" onclick="window.location.href='{% url 'decks:index' %}';" value="Ok" /></div>
        </div>
    </div>
    {% endif %}
</body>

decks/templates/decks/edit_card.html
{% load static %}
<head>
    <title>Magic Library - Decks</title>
    <link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
    <style>
        .addBorder {
            border-collapse: collapse;
        }
        
        .addBorder, .addBorder td, .addBorder th {
            border: 1px solid black;
        }
    </style>
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Magic Library - Decks</h1>
    {% include "decks/horizontal_navigation_bar.html" only %}
    <ul class="horizontal_nav_bar">
        {% for dt in deck_types %}
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">{{ dt.name }}</a>
            <div class="dropdown-content">
                {% for d in dt.sorted_decks %}
                <a href="{% url 'decks:deck' d.id %}">{{d.name}}</a>
                {% endfor %}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'decks:edit_card' deck_card.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" id="hdnAction" value="" />
            <div style="width:500px">
                <div style="float:left">{{deck_card.card.name}}</div>
                <div style="float:right">{% include "cards/mana_view.html" with mana=deck_card.card.manaArr %}</div>
                <div style="clear:both">{{deck_card.card.supertypes}} {{deck_card.card.regular_types}}{% if deck_card.card.sub_types %} &mdash; {{deck_card.card.sub_types}}{% endif %}</div>
                <div style="margin-top:10px">{% autoescape off %}{{deck_card.card.html_text}}{% endautoescape %}</div>
                <hr/>
            </div>
            <div>
                <input type="number" name="count" style="width:50px" min="0" value="{{ deck_card.card.count }}" />
                <label style="margin-left:50px"><input type="checkbox" name="add_mana" {% if deck_card.card.addMana %}checked{% endif %} />Adds Mana</label>
            </div>
            <div style="margin-top:10px">Last Updated: {{ deck_card.card.lastUpdated }}</div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Decks</div>
                {% for oc in other_cards %}
                    <div>
                        {{oc.deck.name}}
                        {% if oc.id == deck_card.id %}
                        (Count <input type="number" name="deck_count" value="{{oc.count}}" min="0" style="width:50px" />, Sideboard <input type="number" name="sideboard_count" value="{{oc.sideboard_count}}" min="0" style="width:50px" /> <label>Commander<input type="checkbox" name="commander" {% if oc.commander %}checked{% endif %}/></label>)
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Notes</div>
                <textarea rows="5" cols="50" name="notes">{{ deck_card.card.notes }}</textarea>
            </div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Sets</div>
                <div>{{deck_card.card.print_sets}}</div>
            </div>
            <div style="margin-top:10px">
                <input type="button" onclick="doSubmit('save')" value="Save" />
                <input type="button" onclick="window.location.href='{% url 'decks:deck' deck_card.deck.id %}';" value="Cancel" />
            </div>
        </form>
    </div>
</body>

decks/templates/decks/horizontal_navigation_bar.html
<ul class="horizontal_nav_bar">
    <li><a href="{% url 'cards:index' %}">Cards</a></li>
    <li><a href="{% url 'decks:index' %}" {% if page_name == "index" %}class="hor_active"{% endif %}>Decks</a></li>
    <li><a href="{% url 'decks:add' %}" {% if page_name == "add" %}class="hor_active"{% endif %}>Add</a></li>
</ul>

decks/templates/decks/m_add.html
{% load static %}
<head>
    <title>Magic Library - Decks</title>
    <link href="{% static 'm_styles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .addBorder {
            border-collapse: collapse;
        }

        .addBorder, .addBorder td, .addBorder th {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    {% include "decks/m_top_bar.html" with deck_types=deck_types %}
    <div style="margin-top:10px; float:left">
        <form id="frmMain" action="{% url 'decks:add' %}" method="post">
            {% csrf_token %}
            <div>Deck Name</div>
            <div style="margin-top:10px"><input type="text" name="name" /></div>
            <div style="margin-top:20px">
                {% for dt in deck_types %}<input type="radio" value="{{dt.id}}" name="deckType" id="rdo{{forloop.counter}}" {% if forloop.counter == 1 %}checked{% endif %}/><label for="rdo{{forloop.counter}}">{{dt.name}}</label>{% endfor %}
            </div>
            <div style="margin-top:20px">Deck List</div>
            <div style="font-size:small">
                <input type="radio" name="inputType" id="input1" checked value="X"><label for="input1">&lt;count&gt;x &lt;card name&gt;</label>
                    <input type="radio" name="inputType" id="input2" value="plain"><label for="input2">&lt;count&gt; &lt;card name&gt;</label>
            </div>
            <div style="margin-top:10px"><textarea name="list" cols="25" rows="20"></textarea></div>
            <div style="margin-top:10px">Sideboard List</div>
            <div style="margin-top:10px"><textarea name="sideboard" cols="25" rows="20"></textarea></div>
            <div style="margin-top:10px">Notes</div>
            <div style="margin-top:10px"><textarea name="notes" style="width:100%" rows="10"></textarea></div>
            <div style="margin-top:10px">
                <input type="submit" value="Save" />
                <input type="button" value="Cancel" onclick="window.location.href='{% url 'decks:index' %}';" />
            </div>
        </form>
    </div>
    {% if error %}
    <div style="margin-top:10px;float:left;text-color:red">{{ error }}</div>
    {% endif %}
    {% if saved %}
    <div class="gray" style="display:block">
        <div class="popup">
            <div>Issue with Deck List</div>
            <div>{{saved}}</div>
            <div><input type="button" onclick="window.location.href='{% url 'decks:deck' new_deck %}';" value="Ok" /></div>
        </div>
    </div>
    {% endif %}
</body>

decks/templates/decks/m_edit_card.html
{% load static %}
<head>
    <title>Magic Library - Decks</title>
    <link href="{% static 'm_styles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .addBorder {
            border-collapse: collapse;
        }

        .addBorder, .addBorder td, .addBorder th {
            border: 1px solid black;
        }
    </style>
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    {% include "decks/m_top_bar.html" with deck_types=deck_types %}
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'decks:edit_card' deck_card.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" id="hdnAction" value="" />
            <div>
                <div style="float:left; font-size:36px">{{deck_card.card.name}}</div>
                <div style="float:right; font-size:36px">{% include "cards/m_mana_view.html" with mana=deck_card.card.manaArr %}</div>
                <div style="clear:both; font-size:36px">{{deck_card.card.supertypes}} {{deck_card.card.regular_types}}{% if deck_card.card.sub_types %} &mdash; {{deck_card.card.sub_types}}{% endif %}</div>
                <div style="margin-top:10px; font-size:36px">{% autoescape off %}{{deck_card.card.html_text}}{% endautoescape %}</div>
                <hr/>
            </div>
            <div>
                <input type="number" name="count" style="width:100px" min="0" value="{{ deck_card.card.count }}" />
                <input id="chk1" type="checkbox" name="add_mana" {% if deck_card.card.addMana %}checked{% endif %} /><label for="chk1">Adds Mana</label>
            </div>
            <div style="margin-top:10px">Last Updated: {{ deck_card.card.lastUpdated }}</div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Decks</div>
                {% for oc in other_cards %}
                    <div>
                        {{oc.deck.name}}
                        {% if oc.id == deck_card.id %}
                        (Count <input type="number" name="deck_count" value="{{oc.count}}" min="0" style="width:100px" />, Sideboard <input type="number" name="sideboard_count" value="{{oc.sideboard_count}}" min="0" style="width:100px" />, <label for="chk2">Commander</label><input id="chk2" type="checkbox" name="commander" {% if oc.commander %}checked{% endif %}/><label for="chk2" class="small"></label>)
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Notes</div>
                <textarea rows="5" style="width:100%" name="notes">{{ deck_card.card.notes }}</textarea>
            </div>
            <div style="margin-top:10px">
                <div style="font-weight:bold">Sets</div>
                <div>{{deck_card.card.print_sets}}</div>
            </div>
            <div style="margin-top:10px">
                <input type="button" onclick="doSubmit('save')" value="Save" />
                <input type="button" onclick="window.location.href='{% url 'decks:deck' deck_card.deck.id %}';" value="Cancel" />
            </div>
        </form>
    </div>
</body>

decks/templates/decks/m_top_bar.html
<script>
    /* Open when someone clicks on the span element */
    function openNav() {
        document.getElementById("myNav").style.width = "100%";
    }

    /* Close when someone clicks on the "x" symbol inside the overlay */
    function closeNav() {
        document.getElementById("myNav").style.width = "0%";
    }
    
    function showDeckTypeMenu(id) {
        var mn = document.getElementById("topmenu"+id);
        if(mn.className == "") {
            mn.className = "selected";
            document.getElementById("menu"+id).style.display = "block";
            document.querySelector("#topmenu"+id +" i").innerText = "remove";
        } else {
            mn.className = "";
            document.getElementById("menu"+id).style.display = "";
            document.querySelector("#topmenu"+id +" i").innerText = "add";
        }
    }
</script>
<div class="topnav">
    <span class="title">Magic Library - Decks</span>
    <div class="icon" onclick="openNav()"><i class="material-icons md-48">menu</i></div>
</div>
<div id="myNav" class="overlay">
  <!-- Button to close the overlay navigation -->
  <div class="closebtn"><a href="javascript:void(0)" onclick="closeNav()">&times;</a></div>

  <!-- Overlay content -->
  <div class="overlay-content">
    <a href="{% url 'cards:index' %}">Cards</a>
    <div class="line"></div>
    <a href="{% url 'decks:index' %}">Types</a>
    <a href="{% url 'decks:add' %}">Add</a>
    {% for dt in deck_types %}
    <a id="topmenu{{dt.id}}" href="javascript:showDeckTypeMenu({{dt.id}})">{{dt.name}}<i class="material-icons md-72" style="float:right">add</i></a>
    <div id="menu{{dt.id}}" class="overlay-menu">
        {% for deck in dt.sorted_decks %}
        <a href="{% url 'decks:deck' deck.id %}">{{ deck.name }}</a>
        {% endfor %}
    </div>
    {% endfor %}
  </div>

</div>