cards/urls.py
from django.urls import path

from . import views

app_name = "cards"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:card_id>/', views.edit, name="edit"),
    path('add_json', views.add_json, name="json"),
]

whiteboard/urls.py
from django.urls import path

from . import views

app_name = "whiteboard"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:whiteboard_id>', views.use, name="use"),
]

whiteboard/models.py
from django.db import models
from django import forms
from django.core.validators import MinValueValidator

class Whiteboard(models.Model):
    name = models.CharField(max_length=200)
    width = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
    height = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
    password = models.CharField(max_length=20)
    
    def create_pixels(self):
        for x in range(self.width):
            for y in range(self.height):
                p = Pixel(board=self,x=x,y=y)
                p.save()

class WhiteboardForm(forms.ModelForm):
    class Meta:
        model = Whiteboard
        fields = "__all__"
        widgets = {'password': forms.PasswordInput()}

class Pixel(models.Model):
    board = models.ForeignKey(Whiteboard,on_delete=models.CASCADE)
    x = models.PositiveSmallIntegerField()
    y = models.PositiveSmallIntegerField()
    colour = models.CharField(max_length=6,default="FFFFFF")
    last_changed = models.DateTimeField(auto_now=True)

whiteboard/views.py
from django.shortcuts import render, redirect
from .models import Whiteboard, Pixel, WhiteboardForm
from django.forms.utils import ErrorList

# Create your views here.
def index(request):
    context = {'boards':Whiteboard.objects.all()}
    return render(request,'whiteboard/index.html',context)

def add(request):
    context = {}
    if request.POST:
        f = WhiteboardForm(request.POST)
        context['form'] = f
        if f.is_valid:
            if request.POST['password'] != request.POST['password_confirm']:
                f.add_error("password","Passwords do not match.")
            else:
                w = f.save()
                w.create_pixels()
                return redirect('whiteboard:index')
    else:
        context['form'] = WhiteboardForm()
    return render(request,'whiteboard/add.html',context)

def use(request,whiteboard_id):
    context = {'board':Whiteboard.objects.get(pk=whiteboard_id)}
    
    return render(request,'whiteboard/use.html',context)

whiteboard/templates/whiteboard/add.html
{% load static %}
<html>
    <head>
        <title>Whiteboards</title>
        <link href="{% static 'styles.css' %}"  type="text/css" rel="stylesheet"></link>
        <style>
            ul {
                list-style-type: none;
            }
            
            li {
                margin-bottom: 10px;
            }
            
            .errorList {
                color: red;
            }
        </style>
    </head>
    <body>
        <h1>Add New Whiteboard</h1>
        <form action="{% url 'whiteboard:add' %}" method="POST">
            {% csrf_token %}
            <ul>
                {{form.as_ul}}
                <li><label for="id_password_confirm">Confirm Password:</label> <input type="password" name="password_confirm" maxlength="20" required id="id_password_confirm"></li>
            </ul>
            <div>
                <input type="submit" value="Save" />
                <input type="button" value="Cancel" onclick="window.location='{% url 'whiteboard:index' %}';" />
            </div>
        </form>
    </body>
</html>

whiteboard/templates/whiteboard/index.html
{% load static %}
<html>
    <head>
        <title>Whiteboards</title>
        <link href="{% static 'styles.css' %}"  type="text/css" rel="stylesheet"></link>
    </head>
    <body>
        <h1>Whiteboards</h1>
        <ul style="list-style-type:none">
            {% for b in boards %}
            <li><a href="{% url 'whiteboard:use' b.id %}">{{ b.name }}</a></li>
            {% endfor %}
        </ul>
        <input type="button" value="Add New Whiteboard" onclick="window.location='{% url 'whiteboard:add' %}';" />
    </body>
</html>

whiteboard/templates/whiteboard/use.html
{% load static %}
<html>
    <head>
        <title>Whiteboards</title>
        <link href="{% static 'styles.css' %}"  type="text/css" rel="stylesheet"></link>
    </head>
    <body>
        <h1>Whiteboard {{board.name}}</h1>
        <a href="{% url 'whiteboard:index' %}">Home</a>
        <div style="margin-top:10px">
            <canvas width="{{board.width}}" height="{{board.height}}" style="border:1px solid black"></canvas>
        </div>
    </body>
</html>