cards/urls.py
from django.urls import path

from . import views

app_name = "cards"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:card_id>/', views.edit, name="edit"),
    path('add_json', views.add_json, name="json"),
]

decks/urls.py
from django.urls import path

from . import views

app_name = "decks"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:deck_id>/', views.detail, name="deck"),
    path('cards/<int:deck_card_id>/', views.edit_card, name="edit_card"),
]

cards/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    name = models.CharField(max_length=200)
    typeType = models.SmallIntegerField() # 1: sub, 2: super, 3: regular
    def __str__(self):
        if self.typeType == 1:
            return "Type: {} (sub)".format(self.name)
        elif self.typeType == 2:
            return "Type: {} (super)".format(self.name)
        elif self.typeType == 3:
            return "Type: {} (regular)".format(self.name)
    
class Set(models.Model):
    name = models.CharField(max_length=100)
    cards = models.ManyToManyField("Card")

class Card(models.Model):
    name = models.CharField(max_length=200)
    types = models.ManyToManyField(Type)
    manaCost = models.CharField(max_length=20,blank=True) # number or number X or colour single or colour P or colour colour
    text = models.TextField(blank=True)
    fancyText = models.TextField(blank=True)
    power = models.CharField(max_length=2,blank=True)
    toughness = models.CharField(max_length=2,blank=True)
    loyalty = models.CharField(max_length=2,blank=True)
    notes = models.TextField(blank=True)
    addMana = models.BooleanField()
    count = models.SmallIntegerField(default=0)
    lastUpdated = models.DateTimeField(auto_now=True)
    
    def cmc(self):
        if self.manaCost == '':
            return ''
        else:
            rv = 0
            for s in self.manaCost.split(','):
                try:
                    rv += int(s)
                except ValueError:
                    if len(s) == 1 or s[1] != 'X':
                        rv += 1
            return rv
            
    def cmc_num(self):
        rv = self.cmc()
        if rv == '':
            return -1
        else:
            return rv
    
    def manaArr(self):
        return self.manaCost.split(',')
    
    def super_types(self):
        rv = ""
        for st in self.types.filter(typeType__exact=2):
            if len(rv) > 0:
                rv = rv + " "
            rv = rv + st.name
        return rv
    
    def regular_types(self):
        rv = ""
        for st in self.types.filter(typeType__exact=3):
            if len(rv) > 0:
                rv = rv + " "
            rv = rv + st.name
        return rv
    
    def sub_types(self):
        rv = ""
        for st in self.types.filter(typeType__exact=1):
            if len(rv) > 0:
                rv = rv + " "
            rv = rv + st.name
        return rv
    
    def plt(self):
        if len(self.loyalty) > 0:
            return self.loyalty
        elif len(self.power) > 0:
            return self.power + "/" +self.toughness
        else:
            return ""
    
    def colours(self):
        rv = 0
        for m in self.manaArr():
            if "W" in m:
                rv = rv | 1
            if "U" in m:
                rv = rv | 2
            if "B" in m:
                rv = rv | 4
            if "R" in m:
                rv = rv | 8
            if "G" in m:
                rv = rv | 16
        return rv
    
    def print_sets(self):
        rv = ""
        for s in self.set_set.all():
            if len(rv) > 0:
                rv = rv + ", "
            rv = rv + s.name
        return rv
    
    def html_text(self):
        return self.text.replace("\n","<br/>").replace("\r","")
    
    def js_text(self):
        return self.text.replace("\n","\\n").replace("\r","").replace('"',"&quot;")

cards/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from .models import Card,Type,Set
from decks.models import Deck,DeckCard
import os, json, re

bad_set_types = ["promo","funny","archenemy","starter","memorabilia"]

class AdvancedSearch:
    allAnd = True
    colourAnd = True
    colourless = False
    colourMask = 0
    superAnd = True
    supers = []
    typeAnd = True
    types = []
    cmc = []
    textAnd = True
    text = []
    noDeck = False
    decks = []
    notesAnd = True
    notes = []
    noNotes = False
    countOperator = 0 #<,<=,=,>=,>
    countNumber = 0
    addsMana = False
    setsAnd = True
    sets = []
    noSets = False

    def matches(self, card):
        results = []
        #colour
        if (not self.colourless) and self.colourMask == 0:
            pass
        elif self.colourAnd:
            #anding
            if self.colourless:
                if self.colourMask != 0:
                    #can't be coloured and colourless
                    results.append(False)
                else:
                    #checking if colourless
                    if card.colours() != 0:
                        results.append(False)
                    else:
                        results.append(True)
            else:
                #checking for colour
                results.append(self.colourMask == card.colours())
        else:
            #oring
            results.append((self.colourMask & card.colours()) != 0 or (self.colourless and card.colours() == 0))
        #supers
        if self.superAnd:
            results.append(True)
            for t in self.supers:
                if len(card.types.filter(id=t)) == 0:
                    results[-1] = False
                    break
        else:
            results.append(False)
            for t in self.supers:
                if len(card.types.filter(id=t)) > 0:
                    results[-1] = True
                    break
        #types
        if self.typeAnd:
            results.append(True)
            for t in self.types:
                if len(card.types.filter(id=t)) == 0:
                    results[-1] = False
                    break
        else:
            results.append(False)
            for t in self.types:
                if len(card.types.filter(id=t)) > 0:
                    results[-1] = True
                    break
        #cmc
        if len(self.cmc) > 0:
            results.append(card.cmc() in self.cmc)
        #text
        if len(self.text) > 0:
            if len(card.text) == 0:
                results.append(False)
            elif self.textAnd:
                results.append(True)
                for t in self.text:
                    if t.lower() not in card.text.lower():
                        results[-1] = False
                        break
            else:
                results.append(False)
                for t in self.text:
                    if t.lower() in card.text.lower():
                        results[-1] = True
                        break
        #decks
        if self.noDeck:
            results.append(len(card.deckcard_set.all()) == 0)
        elif len(self.decks) > 0:
            results.append(False)
            for d in self.decks:
                if card.deckcard_set.filter(deck__name__iexact=d).exists():
                    results[-1] = True
                    break
        #notes
        if len(self.notes) > 0:
            if len(card.notes) == 0:
                results.append(False)
            elif self.notesAnd:
                results.append(True)
                for t in self.notes:
                    if t.lower() not in card.notes.lower():
                        results[-1] = False
                        break
            else:
                results.append(False)
                for t in self.notes:
                    if t.lower() in card.notes.lower():
                        results[-1] = True
                        break
        #card count
        if self.countOperator == 0:
            results.append(card.count < self.countNumber)
        elif self.countOperator == 1:
            results.append(card.count <= self.countNumber)
        elif self.countOperator == 2:
            results.append(card.count == self.countNumber)
        elif self.countOperator == 3:
            results.append(card.count >= self.countNumber)
        elif self.countOperator == 4:
            results.append(card.count > self.countNumber)
        #adds mana
        if self.addsMana:
            results.append(card.addMana)
        #sets
        if self.noSets:
            results.append(len(card.set_set.all()) == 0)
        elif len(self.sets) > 0:
            if self.setsAnd:
                results.append(True)
                for t in self.sets:
                    if len(card.set_set.filter(name__iexact=t)) == 0:
                        results[-1] = False
                        break
            else:
                results.append(False)
                for t in self.sets:
                    if len(card.set_set.filter(name__iexact=t)) > 0:
                        results[-1] = True
                        break
        #results
        rv = self.allAnd
        if self.allAnd:
            for r in results:
                rv = rv and r
        else:
            for r in results:
                rv = rv or r
        return rv


def mobile(request):
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)

    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False

def arrayGet(request, index, is_int):
    if mobile(request):
        return json.loads(request.POST[index])
    elif is_int:
        return list(map(int,request.POST.getlist(index)))
    else:
        return request.POST.getlist(index)

# Create your views here.
def index(request):
    context = None
    try:
        action = request.POST['action']
        if action == "search" and len(request.POST["simple_search"]) > 0:
            context = {"search_results":Card.objects.filter(name__startswith=request.POST["simple_search"]).order_by('name'),"simple_search":request.POST["simple_search"]}
        elif action == "switcha" or action == "advanced":
            context = {"isadvanced":"isadvanced","supers":Type.objects.filter(typeType=2).order_by('name'),
                "types":Type.objects.filter(typeType=3).order_by('name'),"countOperator":3,"countNumber":0,"deck_list":Deck.objects.all().order_by("name")}
            if action == "advanced":
                avs = AdvancedSearch()
                avs.allAnd = "andAll" not in request.POST.keys()
                if not avs.allAnd:
                    context["andAll"] = "andAll"
                #Colour
                avs.colourAnd = "andColour" not in request.POST.keys()
                if not avs.colourAnd:
                    context["andColour"] = "andColour"
                avs.colourless = "colourless" in request.POST.keys()
                if avs.colourless:
                    context["colourless"] = "colourless"
                if "white" in request.POST.keys():
                    avs.colourMask = avs.colourMask | 1
                    context["white"] = "white"
                if "blue" in request.POST.keys():
                    avs.colourMask = avs.colourMask | 2
                    context["blue"] = "blue"
                if "black" in request.POST.keys():
                    avs.colourMask = avs.colourMask | 4
                    context["black"] = "black"
                if "red" in request.POST.keys():
                    avs.colourMask = avs.colourMask | 8
                    context["red"] = "red"
                if "green" in request.POST.keys():
                    avs.colourMask = avs.colourMask | 16
                    context["green"] = "green"
                #supers and types
                avs.superAnd = "andSuper" not in request.POST.keys()
                if not avs.superAnd:
                    context["andSuper"] = "andSuper"
                context["typeChecked"] = []
                avs.typeAnd = "andType" not in request.POST.keys()
                if not avs.typeAnd:
                    context["andType"] = "andType"
                context["superChecked"] = []
                for k in request.POST.keys():
                    if k.startswith("type-"):
                        context["typeChecked"].append(int(k[5:]))
                        avs.types.append(int(k[5:]))
                    elif k.startswith("super-"):
                        context["superChecked"].append(int(k[6:]))
                        avs.supers.append(int(k[6:]))
                #cmc
                context["cmc"] = request.POST["cmc"]
                if len(context["cmc"]) > 0:
                    for c in context["cmc"].split(","):
                        avs.cmc.append(int(c))
                #text
                avs.textAnd = "andText" not in request.POST.keys()
                if not avs.textAnd:
                    context["andText"] = "andText"
                context["text"] = request.POST["text"]
                if len(context["text"]) > 0:
                    avs.text = context["text"].split(os.linesep)
                #decks
                avs.noDeck = "nodeck" in request.POST
                if avs.noDeck:
                    context["nodeck"] = "nodeck"
                context["decks"] = request.POST["decks"]
                if len(context["decks"]) > 0:
                    for d in context["decks"].split(","):
                        avs.decks.append(d)
                #notes
                avs.notesAnd = "andNotes" not in request.POST.keys()
                if not avs.notesAnd:
                    context["andNotes"] = "andNotes"
                context["notes"] = request.POST["notes"]
                if len(context["notes"]) > 0:
                    avs.notes = context["notes"].split(os.linesep)
                #card count

cards/templates/cards/add_json.html
{% load static %}
<head>
    <title>Magic Library - Cards</title>
    <link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Magic Library - Cards</h1>
    {% include "cards/horizontal_navigation_bar.html" with page_name='json' %}
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'cards:json' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input type="hidden" name="action" id="hdnAction" value="search" />
            <div>
                <input type="text" id="txtName" name="name" value="{{ name }}" />
                <input type="submit" value="Search" />
            </div>
            <div style="margin-top:10px">
                <select name="cards" style="width:450px" size="5" multiple>
                    {% for result in results %}
                    <option value="{{ result }}">{{ result }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>* - already in database</div>
            <div style="margin-top:10px">Own Count</div>
            <div><input type="number" min="0" value="0" name="own_count"></div>
            <div style="margin-top:10px">Add to Decks</div>
            <div style="margin-top:10px">
                <select name="deck_choices" style="width:225px" size="5" multiple>
                    {% for d in decks %}
                    <option value="{{d.id}}" {% if d.id in deck_choices %}selected{% endif %}>{{d.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label><input type="checkbox" name="add_sideboard" {% if add_sideboard %}checked{% endif %} />Add to Sideboard</label>
            </div>
            <div style="margin-top:10px">Add to Notes</div>
            <div style="margin-top:10px"><textarea rows="5" cols="30" name="notes">{{ notes }}</textarea></div>
            <div style="margin-top:10px">
                <input type="button" onclick="doSubmit('add')" value="Add" />
                <input type="button" onclick="doSubmit('addp')" value="Add +" />
                <input type="button" onclick="window.location.href='{% url 'cards:index' %}'" value="Cancel" />
            </div>
        </form>
    </div>
    <script>
        document.getElementById("txtName").focus();
        {% if name %}
        document.getElementById("txtName").setSelectionRange({{ name|length }},{{ name|length }});
        {% endif %}
    </script>
</body>

cards/templates/cards/horizontal_navigation_bar.html
<ul class="horizontal_nav_bar">
    <li><a href="{% url 'decks:index' %}">Decks</a></li>
    <li><a href="{% url 'cards:index' %}" {% if page_name == "search" %}class="hor_active"{% endif %}>Search</a></li>
    <li><a href="{% url 'cards:add' %}" {% if page_name == "add" %}class="hor_active"{% endif %}>Add</a></li>
    <li><a href="{% url 'cards:json' %}" {% if page_name == "json" %}class="hor_active"{% endif %}>Add JSON</a></li>
</ul>

cards/templates/cards/index.html
{% load static %}
<head>
    <title>Magic Library - Cards</title>
    <link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
    <style>
        .addBorder {
            border-collapse: collapse;
        }
        
        .addBorder, .addBorder td, .addBorder th {
            border: 1px solid black;
        }
    </style>
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Magic Library - Cards</h1>
    {% include "cards/horizontal_navigation_bar.html" with page_name="search" %}
    {{test}}
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'cards:index' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" id="hdnAction" value="search" />
            {% if isadvanced %}
            <div style="float:left;margin-top:10px">
                <div>Search:</div>
                <div style="margin-top:5px; font-size:10px">And<label class="switch"><input type="checkbox" name="andAll" {% if andAll %}checked{% endif %} /><span class="slider"></span></label>Or</div>
                <div style="margin-top:10px"><span class="search-header">Colour</span><span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andColour" {% if andColour %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span></div>
                <div style="margin-top:5px">
                    <div>
                    <label><input type="checkbox" name="white" {% if white %}checked{% endif %} />White</label>
                    <label><input type="checkbox" name="blue" {% if blue %}checked{% endif %} />Blue</label>
                    <label><input type="checkbox" name="black" {% if black %}checked{% endif %} />Black</label>
                    </div><div>
                    <label><input type="checkbox" name="red" {% if red %}checked{% endif %} />Red</label>
                    <label><input type="checkbox" name="green" {% if green %}checked{% endif %} />Green</label>
                    <label><input type="checkbox" name="colourless" {% if colourless %}checked{% endif %} />Colourless</label>
                    </div>
                </div>
                {% if supers %}
                <div style="margin-top:10px"><span class="search-header">Supertype</span><span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andSuper" {% if andSuper %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span></div>
                <div style="margin-top:5px">
                    <div>
                    {% for t in supers %}
                    <label><input type="checkbox" name="super-{{ t.id }}" {% if t.id in superChecked %}checked{% endif %} />{{ t.name }}</label>
                    {% if forloop.counter|divisibleby:3 %}</div><div>{% endif %}
                    {% endfor %}
                    </div>
                </div>
                {% endif %}
                <div style="margin-top:10px"><span class="search-header">Type</span><span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andType" {% if andType %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span></div>
                <div style="margin-top:5px">
                    <div>
                    {% for t in types %}
                    <label><input type="checkbox" name="type-{{ t.id }}" {% if t.id in typeChecked %}checked{% endif %} />{{ t.name }}</label>
                    {% if forloop.counter|divisibleby:3 %}</div><div>{% endif %}
                    {% endfor %}
                    </div>
                </div>
                <div style="margin-top:10px"><span class="search-header">CMC</span><span style="font-size:10px">(comma seperated)</span></div>
                <div style="margin-top:5px"><input type="text" name="cmc" value="{{ cmc }}" /></div>
                <div style="margin-top:10px"><span class="search-header">Rules Text</span><span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andText" {% if andText %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span></div>
                <div style="margin-top:5px">
                    <textarea name="text" rows="5" cols="25">{{ text }}</textarea>
                </div>
                <div style="margin-top:10px">
                    <span class="search-header">Decks</span><span style="font-size:10px">(comma seperated)</span>
                    <input type="button" onclick="document.getElementById('divDeckList').style.display='block';" value="View List" />
                    <label><input type="checkbox" name="nodeck" {% if nodeck %}checked{% endif %} />Not in a deck</label>
                </div>
                <div style="margin-top:5px">
                    <input type="text" name="decks" value="{{decks}}" />
                </div>
                <div style="margin-top:10px"><span class="search-header">Notes</span><span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andNotes" {% if andNotes %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span></div>
                <div style="margin-top:5px">
                    <textarea name="notes" rows="5" cols="25">{{ notes }}</textarea>
                </div>
                <div style="margin-top:10px"><span class="search-header">Card Count</span></div>
                <div style="margin-top:5px">
                    <select name="countOperator">
                        <option value="0" {% if countOperator == 0 %}selected{% endif %}>&lt;</option>
                        <option value="1" {% if countOperator == 1 %}selected{% endif %}>&lt;=</option>
                        <option value="2" {% if countOperator == 2 %}selected{% endif %}>=</option>
                        <option value="3" {% if countOperator == 3 %}selected{% endif %}>&gt;=</option>
                        <option value="4" {% if countOperator == 4 %}selected{% endif %}>&gt;</option>
                    </select>
                    <input type="number" name="countNumber" min="0" value="{{ countNumber }}" style="width:50px" />
                </div>
                <div style="margin-top:10px"><label class="search-header">Adds Mana<input type="checkbox" name="addsMana" {% if addsMana %}checked{% endif %}/></label></div>
                <div style="margin-top:10px"><span class="search-header">Sets</span><span style="font-size:10px">(comma seperated)</span>
                    <span style="font-size:10px">And</span><label class="switch"><input type="checkbox" name="andSets" {% if andSets %}checked{% endif %} /><span class="slider"></span></label><span style="font-size:10px">Or</span>
                    <label><input type="checkbox" name="nosets" {% if nosets %}checked{% endif %} />Has no sets</label></div>
                <div style="margin-top:5px"><input type="text" name="sets" value="{{ sets }}" /></div>
                <div style="margin-top:5px">
                    <input type="button" value="Search" onclick="doSubmit('advanced')" />
                    <input type="button" value="Reset" onclick="doSubmit('switcha')" />
                    <input type="button" value="Simple" onclick="doSubmit('switchs')" />
                </div>
            </div>
            {% else %}
            <div>
                <span>Search:</span>
                <input name="simple_search" type="text" {% if simple_search %}value="{{ simple_search }}"{% endif%} />
                <input type="submit" value="Search" />
                <input type="button" value="Advanced" onclick="doSubmit('switcha')" />
            </div>
            {% endif %}
            <div style="margin-top:10px{% if isadvanced %};float:left;margin-left:10px;padding-bottom:8px{% endif %}">
                {% if search_results %}
                <table class="addBorder" style="text-align:center">
                    <tr>
                        <th>Name</th>
                        <th>Mana</th>
                        <th>CMC</th>
                        <th>Type</th>
                        <th>Count</th>
                    </tr>
                    {% for result in search_results %}
                    <tr>
                        <td><a href="{% url 'cards:edit' result.id%}">{{ result.name }}</a></td>
                        <td style="padding-left:5px;padding-right:5px">{% include "cards/mana_view.html" with mana=result.manaArr %}</td>
                        <td>{{ result.cmc }}</td>
                        <td>{{ result.regular_types }}</td>
                        <td>{{ result.count }}</td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <div style="margin-top:10px">No results found</div>
                {% endif %}
            </div>
        </form>
    </div>
    {% if deck_list %}
    <div class="gray" id="divDeckList">
        <div class="popup">
            <div>Decks</div>
            {% for d in deck_list %}
            <div>{{d.name}}</div>
            {% endfor %}
            <div><input type="button" onclick="document.getElementById('divDeckList').style.display='';" value="OK" /></div>
        </div>
    </div>
    {% endif %}
</body>

cards/templates/cards/m_add_json.html
{% load static %}
<head>
    <title>Magic Library - Cards</title>
    <link href="{% static 'm_styles.css' %}" type="text/css" rel="stylesheet"></link>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }

        function updateList(id, value) {
            var hdn = document.getElementById("hdn" +id);
            var lst = JSON.parse(hdn.value);
            var ind = lst.indexOf(value);
            if(ind < 0) {
                lst.splice(-1,0,value.replace("&#39;","'"));
                document.getElementById(id+value).className = "selected";
            } else {
                lst.splice(ind,1);
                document.getElementById(id+value).className = "";
            }
            hdn.value = JSON.stringify(lst);
        }
    </script>
</head>
<body>
    {% include "cards/m_top_bar.html" %}
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'cards:json' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input type="hidden" name="action" id="hdnAction" value="search" />
            <div>
                <input type="search" id="txtName" name="name" value="{{ name }}" />
                <input type="submit" value="Search" />
            </div>
            <div style="margin-top:10px; width:500px;">
                <input type="hidden" name="cards" id="hdncards" value="[]" />
                <ul id="cards" class="select" style="height: 240px; overflow-y:auto">
                    {% for result in results %}
                    <li id="cards{{result}}" onclick="updateList('cards','{{result}}')">{%autoescape off%}{{ result }}{%endautoescape%}</li>
                    {% endfor %}
                </ul>
            </div>
            <div>* - already in database</div>
            <div style="margin-top:10px">Own Count</div>
            <div><input type="number" min="0" value="0" name="own_count"></div>
            <div style="margin-top:10px">Add to Decks</div>
            <div style="margin-top:10px; width:500px;">
                <input type="hidden" name="deck_choices" id="hdndeck_choices" value="{{deck_choices}}" />
                <ul id="deck_choices" class="select" style="height: 240px; overflow-y:auto">
                    {% for d in decks %}
                    <li id="deck_choices{{d.id}}" onclick="updateList('deck_choices',{{d.id}})" {% if d.id in deck_choices %}class="selected"{% endif %}>{{d.name}}</li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <input type="checkbox" name="add_sideboard" id="chk1" {% if add_sideboard %}checked{% endif %} />
                <label for="chk1">Add to Sideboard</label>
            </div>
            <div style="margin-top:10px">Add to Notes</div>
            <div style="margin-top:10px"><textarea rows="5" cols="30" name="notes">{{ notes }}</textarea></div>
            <div style="margin-top:10px">
                <input type="button" onclick="doSubmit('add')" value="Add" />
                <input type="button" onclick="doSubmit('addp')" value="Add +" />
                <input type="button" onclick="window.location.href='{% url 'cards:index' %}'" value="Cancel" />
            </div>
        </form>
    </div>
    <script>
        document.getElementById("txtName").focus();
        {% if name %}
        document.getElementById("txtName").setSelectionRange({{ name|length }},{{ name|length }});
        {% endif %}
    </script>
</body>

cards/templates/cards/m_top_bar.html
<script>
    /* Open when someone clicks on the span element */
    function openNav() {
        document.getElementById("myNav").style.width = "100%";
    }

    /* Close when someone clicks on the "x" symbol inside the overlay */
    function closeNav() {
        document.getElementById("myNav").style.width = "0%";
    }
</script>
<div class="topnav">
    <span class="title">Magic Library - Cards</span>
    <div class="icon" onclick="openNav()"><i class="material-icons md-48">menu</i></div>
</div>
<div id="myNav" class="overlay">
  <!-- Button to close the overlay navigation -->
  <div class="closebtn"><a href="javascript:void(0)" onclick="closeNav()">&times;</a></div>

  <!-- Overlay content -->
  <div class="overlay-content">
    <a href="{% url 'decks:index' %}">Decks</a>
    <div class="line"></div>
    <a href="{% url 'cards:index' %}">Search</a>
    <a href="{% url 'cards:add' %}">Add</a>
    <a href="{% url 'cards:json' %}">Add JSON</a>
  </div>

</div>