cards/urls.py
from django.urls import path

from . import views

app_name = "cards"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:card_id>/', views.edit, name="edit"),
    path('add_json', views.add_json, name="json"),
]

knitting_counter/urls.py
from django.urls import path

from . import views

app_name = "knitting_counter"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:project_id>', views.use, name="use"),
    path('<int:project_id>/edit', views.edit, name="edit"),
]

knitting_counter/models.py
from django.db import models
from django import forms

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    last_updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

class Counter(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    count = models.SmallIntegerField(default=0)
    use_repeats = models.BooleanField(default=False)
    repeat_size = models.SmallIntegerField(default=0)
    repeat_count = models.SmallIntegerField(default=0)
    last_updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name
        
    def dumps(self):
        return {'name':self.name,'count':self.count,'use_repeats':self.use_repeats,
            'repeat_size':self.repeat_size,'repeat_count':self.repeat_count}
    
    def loads(self, d):
        self.name = d['name']
        self.count = d['count']
        self.use_repeats = d['use_repeats']
        self.repeat_size = d['repeat_size']
        self.repeat_count = d['repeat_count']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"

class CounterForm(forms.ModelForm):
    class Meta:
        model = Counter
        exclude = ['project']

knitting_counter/views.py
from django.shortcuts import render, redirect
from .models import Project, Counter, ProjectForm, CounterForm
import json

def get_counters(arr):
    c = []
    for val in arr:
        co = Counter()
        co.loads(val)
        c.append(co)
    return c

def str_counters(arr):
    c = []
    for val in arr:
        c.append(val.dumps())
    return json.dumps(c)

# Create your views here.
def index(request):
    context = {'projects':Project.objects.all().order_by('last_updated')}
    return render(request, 'knitting_counter/index.html', context)

def add(request):
    context = {}
    if request.POST:
        context['form'] = ProjectForm(request.POST,prefix="project")
        counters = get_counters(json.loads(request.POST['counters']))
        action = request.POST['action']
        if action == 'change':
            if request.POST['counter_id'] == '-1':
                context['cform'] = CounterForm(prefix='counter')
                context['counter_id'] = -1
            elif request.POST['counter_id'] != "":
                context['counter_id'] = int(request.POST['counter_id'])
                context['cform'] = CounterForm(instance=counters[context['counter_id']],prefix='counter')
        elif action == 'counter':
            cf = CounterForm(request.POST,prefix='counter')
            if cf.is_valid():
                c = cf.save(commit=False)
                if request.POST['counter_id'] == '-1':
                    counters.append(c)
                elif request.POST['counter_id'] != "":
                    counters[int(request.POST['counter_id'])] = c
            else:
                context['cform'] = cf
                if request.POST['counter_id'] == '-1':
                    counters.append(c)
                elif request.POST['counter_id'] != "":
                    counters[int(request.POST['counter_id'])] = c
                context['counter_id'] = int(request.POST['counter_id'])
        elif action == "save":
            if context['form'].is_valid():
                good = True
                if request.POST['counter_id'] != "":
                    cf = CounterForm(request.POST,prefix='counter')
                    if cf.is_valid():
                        c = cf.save(commit=False)
                        if request.POST['counter_id'] == '-1':
                            counters.append(c)
                        elif request.POST['counter_id'] != "":
                            counters[int(request.POST['counter_id'])] = c
                    else:
                        context['cform'] = cf
                        if request.POST['counter_id'] == '-1':
                            counters.append(c)
                        elif request.POST['counter_id'] != "":
                            counters[int(request.POST['counter_id'])] = c
                        context['counter_id'] = int(request.POST['counter_id'])
                        good = False
                if good:
                    p = context['form'].save()
                    for c in counters:
                        c.project = p
                        c.save()
                    return redirect('knitting_counter:use',p.id)
        context['counters'] = counters
        context['cstr'] = str_counters(counters)
    else:
        context['form'] = ProjectForm(prefix="project")
        context['cstr'] = '[]'
    return render(request, 'knitting_counter/add.html', context)

def use(request, project_id):
    context = {'project':Project.objects.get(pk=project_id)}
    if request.POST:
        context['current_counter'] = int(request.POST['current_counter'])
        for c in context['project'].counter_set.all():
            c.count = int(request.POST['count-{}'.format(c.id)])
            c.repeat_count = int(request.POST['repeat_count-{}'.format(c.id)])
            c.save()
        if request.POST['action'] == 'save':
            return redirect('knitting_counter:index')
    else:
        context['current_counter'] = context['project'].counter_set.all()[0].id
    return render(request, 'knitting_counter/use.html', context)

def edit(request, project_id):
    context = {'project':Project.objects.get(pk=project_id)}
    if request.POST:
        context['form'] = ProjectForm(request.POST, instance=context['project'], prefix='project')
        action = request.POST['action']
        if action == 'change':
            if request.POST['counter_id'] == '-1':
                context['cform'] = CounterForm(prefix='counter')
                context['counter_id'] = -1
            elif request.POST['counter_id'] != "":
                context['counter_id'] = int(request.POST['counter_id'])
                context['cform'] = CounterForm(instance=Counter.objects.get(pk=context['counter_id']),prefix='counter')
        elif action == 'counter':
            cf = CounterForm(request.POST,prefix='counter')
            if cf.is_valid():
                if request.POST['counter_id'] == '-1':
                    c = cf.save(commit=False)
                    c.project = context['project']
                    c.save()
                elif request.POST['counter_id'] != "":
                    cf.instance = Counter.objects.get(pk=request.POST['counter_id'])
                    c = cf.save(commit=False)
                    c.project = context['project']
                    c.save()
            else:
                context['cform'] = cf
                context['counter_id'] = int(request.POST['counter_id'])
        elif action == 'dcounter':
            Counter.objects.get(pk=request.POST['counter_id']).delete()
        elif action == "save" or action == "use":
            if request.POST['counter_id'] != "":
                cf = CounterForm(request.POST,prefix='counter')
                if cf.is_valid():
                    if request.POST['counter_id'] == '-1':
                        c = cf.save(commit=False)
                        c.project = context['project']
                        c.save()
                    elif request.POST['counter_id'] != "":
                        cf.instance = Counter.objects.get(pk=request.POST['counter_id'])
                        c = cf.save(commit=False)
                        c.project = context['project']
                        c.save()
                    if context['form'].is_valid():
                        context['form'].save()
                        if action == "save":
                            return redirect('knitting_counter:index')
                        else:
                            return redirect('knitting_counter:use', project_id=project_id)
                else:
                    context['cform'] = cf
                    context['counter_id'] = int(request.POST['counter_id'])
            elif context['form'].is_valid():
                context['form'].save()
                if action == "save":
                    return redirect('knitting_counter:index')
                else:
                    return redirect('knitting_counter:use', project_id=project_id)
    else:
        context['form'] = ProjectForm(instance=context['project'], prefix='project')
    return render(request, 'knitting_counter/edit.html', context)
    

knitting_counter/templates/knitting_counter/add.html
{% load static %}
<head>
    <title>Knitting Counters</title>
    <link href="{% static 'kstyles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Add New Project</h1>
    <form id="frmMain" action="{% url 'knitting_counter:add' %}" method="post">
        {% csrf_token %}
        <input type="hidden" id="hdnAction" name="action" value="save" />
        <ul class="ul-form">
            {{form.as_ul}}
        </ul>
        <h2>Counters</h2>
        <select name="counter_id" onchange="doSubmit('change')">
            <option value=""{% if not counter_id %} selected{% endif %}></option>
            <option value="-1"{% if counter_id == -1 %} selected{% endif %}>Add New Counter</option>
            {% for c in counters %}
            <option value="{{forloop.counter0}}"{% if counter_id == forloop.counter0 %} selected{% endif %}>{{c.name}}</option>
            {% endfor %}
        </select>
        <input type="hidden" name="counters" value="{{cstr}}" />
        {% if cform %}
        <ul class="ul-form">
            {{cform.as_ul}}
        </ul>
        <button type="button" class="button2" onclick="doSubmit('counter')">Save Counter</button>
        {% endif %}
        <div style="margin-top:10px"><button type="submit" class="button2">Save Project</button></div>
    </form>
</body>

knitting_counter/templates/knitting_counter/edit.html
{% load static %}
<head>
    <title>Knitting Counters</title>
    <link href="{% static 'kstyles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Edit Project</h1>
    <form id="frmMain" action="{% url 'knitting_counter:edit' project.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" id="hdnAction" name="action" value="save" />
        <ul class="ul-form">
            {{form.as_ul}}
        </ul>
        <h2>Counters</h2>
        <select name="counter_id" onchange="doSubmit('change')">
            <option value=""{% if not counter_id %} selected{% endif %}></option>
            <option value="-1"{% if counter_id == -1 %} selected{% endif %}>Add New Counter</option>
            {% for c in project.counter_set.all %}
            <option value="{{c.id}}"{% if counter_id == c.id %} selected{% endif %}>{{c.name}}</option>
            {% endfor %}
        </select>
        {% if cform %}
        <ul class="ul-form">
            {{cform.as_ul}}
        </ul>
        <button type="button" class="button2" onclick="doSubmit('counter')">Save Counter</button>
        {% if counter_id != -1 %}<button type="button" class="button2" onclick="doSubmit('dcounter')">Delete Counter</button>{% endif %}
        {% endif %}
        <div style="margin-top:10px">
            <button type="submit" class="button2">Save Project</button>
            <button type="button" class="button2" onclick="doSubmit('use')">Save and Use Project</button>
            <button type="button" class="button2" onclick="window.location='{% url 'knitting_counter:index' %}">Cancel</button>
        </div>
    </form>
</body>

knitting_counter/templates/knitting_counter/index.html
{% load static %}
<head>
    <title>Knitting Counters</title>
    <link href="{% static 'kstyles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .button1 {
            background-color: #1976d2;
            border: none;
            color: white;
            padding: 5px 5px;
            border-radius: 8px;
            text-align: center;
            text-decoration: none;
            cursor: pointer;
        }
        
        /* Rules for sizing the icon. */
        .material-icons.md-18 { font-size: 18px; }
        .material-icons.md-24 { font-size: 24px; }
        .material-icons.md-36 { font-size: 36px; }
        .material-icons.md-48 { font-size: 48px; }

    </style>
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
    </script>
</head>
<body>
    <h1>Knitting Counters</h1>
    <form id="frmMain" action="{% url 'knitting_counter:index' %}" method="post">
        {% csrf_token %}
        <input type="hidden" id="hdnAction" name="action" value="list" />
        <button type="button" class="button1" onclick="window.location='{% url 'knitting_counter:add' %}';"><i class="material-icons md-36">add</i></button>
        {% if p.len > 0 %}
        {% for p in projects %}
        <div class="row" onclick="window.location='{% url 'knitting_counter:use' p.id %}'">
            <div style="float:left">{{p.name}}</div>
            <div style="float:right">
                <a class="button" href="{% url 'knitting_counter:edit' p.id %}"><i class="material-icons">edit</i></a>
                <a class="button" href="javascript:doSubmit('delete{{p.id}}')"><i class="material-icons">delete</i></a>
            </div>
            <div style="clear:both"></div>
        </div>
        {% endfor %}
        {% endif %}
    </form>
</body>

knitting_counter/templates/knitting_counter/use.html
{% load static %}
<head>
    <title>Knitting Counters</title>
    <link href="{% static 'kstyles.css' %}" type="text/css" rel="stylesheet"></link>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
        function doSubmit(action) {
            document.getElementById("hdnAction").value = action;
            document.getElementById("frmMain").submit();
        }
        
        var current_counter = {{current_counter}};
        
        function changeCounter(id) {
            if(current_counter != id) {
                document.getElementById("display"+current_counter).style.display = "none";
                document.getElementById("display"+id).style.display = "";
                document.getElementById("hdnCurrentCounter").value = id;
                current_counter = id;
            }
        }
        
        {% for c in project.counter_set.all %}
        function increment{{c.id}}() {
            var val = document.getElementById("hdnCount{{c.id}}").value;
            val++;
            {% if c.use_repeats %}
            if(val > {{c.repeat_size}}) {
                val = 1;
                var r = document.getElementById("hdnRepeat{{c.id}}").value;
                r++;
                document.getElementById("hdnRepeat{{c.id}}").value = r;
                document.getElementById("repeat{{c.id}}").innerText = r;
            }
            {% endif %}
            document.getElementById("hdnCount{{c.id}}").value = val;
            document.getElementById("row{{c.id}}").innerText = val;
        }
        
        function decrement{{c.id}}() {
            var val = document.getElementById("hdnCount{{c.id}}").value;
            val--;
            {% if c.use_repeats %}
            var r = document.getElementById("hdnRepeat{{c.id}}").value;
            if(val < 1 && r > 0) {
                val = {{c.repeat_size}};
                r--;
                document.getElementById("hdnRepeat{{c.id}}").value = r;
                document.getElementById("repeat{{c.id}}").innerText = r;
            } else if(val < 0) {
                val = 0;
            }
            {% else %}
            if(val < 0) {
                val = 0;
            }
            {% endif %}
            document.getElementById("hdnCount{{c.id}}").value = val;
            document.getElementById("row{{c.id}}").innerText = val;
        }
        {% endfor %}
    </script>
</head>
<body>
    <h1>{{project.name}} <a href="{% url 'knitting_counter:edit' project.id %}" class="button"><i class="material-icons">edit</i></a></h1>
    {% for c in project.counter_set.all %}
    <div class="counter-display">
        <button type="button" onclick="changeCounter({{c.id}})" class="button5">{{c.name}}</button>
        <div id="display{{c.id}}"{% if current_counter != c.id %} style="display:none"{% endif %}>
            <table>
                <tr>
                    <td style="height:100%"></td>
                    <td rowspan="5"><button type="button" class="button4" onclick="increment{{c.id}}()"><i class="material-icons md-48">add</i></button></td>
                </tr>
                <tr>
                    <td>Row</td>
                </tr>
                <tr>
                    <td id="row{{c.id}}">{{c.count}}</td>
                </tr>
                <tr>
                    <td>Repeat</td>
                </tr>
                <tr>
                    <td id="repeat{{c.id}}">{{c.repeat_count}}</td>
                </tr>
                <tr>
                    <td></td>
                    <td rowspan="4"><button type="button" class="button1" style="width:100%" onclick="decrement{{c.id}}()"><i class="material-icons md-48">remove</i></button></td>
                </tr>
            </table>
        </div>
    </div>
    {% endfor %}
    <div style="margin-top:10px">
        <form id="frmMain" action="{% url 'knitting_counter:use' project.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button2">Save</button>
            <button type="button" class="button2" onclick="doSubmit('save')">Save and Close</button>
            <input type="hidden" id="hdnAction" name="action" value="save+" />
            <input type="hidden" id="hdnCurrentCounter" name="current_counter" value="{{current_counter}}" />
            {% for c in project.counter_set.all %}
            <input type="hidden" id="hdnCount{{c.id}}" value="{{c.count}}" name="count-{{c.id}}" />
            <input type="hidden" id="hdnRepeat{{c.id}}" value="{{c.repeat_count}}" name="repeat_count-{{c.id}}" />
            {% endfor %}
        </form>
    </div>
</body>